# -*- coding: utf-8 -*-
"""tabula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rtM6GceJxGqcWJjccBZaGtmOswhMRtSo
"""

pip install tabula-py

from tabula import read_pdf
from tabulate import tabulate

df = read_pdf("https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",pages=1)
df